language: java
jdk:
  - openjdk11

sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту JekHamond@tutanota.com(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -JekHamond@tutanota.com
    on_success: never # default: change
    on_failure: always # default: always